accounts/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
]

myapp/api/urls.py
from django.conf.urls import url
from myapp.api.views import BlogAPIView

urlpatterns = [
    url('post', BlogAPIView.as_view()),
]

myapp/urls.py
from django.urls import path

from .views import HomePageView
app_name = 'myapp'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from mysite import settings

urlpatterns = [
  path('admin/', admin.site.urls),

  path('', include('myapp.urls', namespace='myapp')),

  path('accounts/', include('accounts.urls')),
  path('api/accounts/', include('accounts.api.urls')),
  path('api/', include('myapp.api.urls')),
  ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.contrib.auth.models import User
from django.db import models

from rest_framework.authtoken.models import Token


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    image = models.FileField(upload_to='post_images')
    category = models.ForeignKey('Category', related_name='posts', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


def __str__(self):
    return f'{self.title} {self.update_at} | {self.published}'


class Category(models.Model):
    name = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

#
# @receiver(post_save, sender=settings.AUTH_USER_MODEL)
# def create_auth_token(sender, instance=None, created=False, **kwargs):
#     if created:
#         Token.objects.create(user=instance)

myapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth import get_user_model, password_validation
from django.core.mail import send_mail
from django.contrib.auth import  get_user_model


User = get_user_model()


# class UserCreationForm(forms.ModelForm):
#     username = forms.CharField(max_length=80)
#     email = forms.EmailField()
#     password1 = forms.CharField(widget=forms.PasswordInput)
#     password2 = forms.CharField(widget=forms.PasswordInput)
#
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']

class RegisterForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput,
                               help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    email = forms.EmailField()

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password2'):
            raise forms.ValidationError('Passwords are not equal')
        password_validation.validate_password(self.cleaned_data.get('password'), None)
        return self.cleaned_data

    def save(self):
        User.objects.create_user(
            username=self.cleaned_data['username'],
            password=self.cleaned_data['password'],
            email=self.cleaned_data['email']
        )
        send_mail(
            'Send mail',
            'Welcome my  Blog',
            'aydin.aliyev058@gmail.com',
            [self.cleaned_data['email']]
        )


# class RegisterForm(UserCreationForm):
#     password1 = forms.CharField(widget=forms.PasswordInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Password',
#     }), )
#     password2 = forms.CharField(widget=forms.PasswordInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Confirm password',
#     }), )
#
#     class Meta:
#         model = User
#         widgets = {
#             'first_name': forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'First name',
#             }),
#             'email': forms.EmailInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Email',
#             }),
#             'username': forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Username',
#             }),
#             'last_name': forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'placeholder': 'Last name',
#             }),
#
#         }
#         fields = ['first_name', 'last_name', 'username', 'email',
#                   'password1', 'password2']


class UserLoginForm(AuthenticationForm):
    username = UsernameField(label="", widget=forms.TextInput(
        attrs={'autofocus': True, 'class': 'form-control', 'placeholder': 'Username', }))
    password = forms.CharField(label="", strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password', }), )

myapp/api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView

from myapp.api.serializers import BlogPostSerializer
from myapp.models import Post, Category


class BlogAPIView(APIView):
    serializer_class = BlogPostSerializer

    # permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    @staticmethod
    def get_queryset():
        post = Post.objects.all()
        return post

    def get(self, request, *args, **kwargs):
        post = self.get_queryset()
        serializer = BlogPostSerializer(post, many=True)

        return Response(serializer.data)

    def post(self, request, *args, **kwargs):
        serializer = BlogPostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(serializer.data)

# class CategoryAPIView(APIView):
#     serializer_class = CategorySerializer
#
#     @staticmethod
#     def get_queryset():
#         category = Category.objects.all()
#         return category
#
#     def get(self, request, *args, **kwargs):
#         category = self.get_queryset()
#         serializer = CategorySerializer(category, many=True)
#
#         return Response(serializer.data)

myapp/views.py
from django.views.generic import ListView

from myapp.models import Post, Category


class HomePageView(ListView):
    model = Post
    template_name = 'index.html'
    context_object_name = 'post_list'
    cat = Category

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        context['category_list'] = Category.objects.all()
        return context

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    {% block body %}

    {% endblock body %}
</body>
</html>

myapp/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div>
    <ul>
        {% if request.user.is_authenticated %}
            You are logged in as {{ user }}
        {% else %}
            You are not logged in.
        {% endif %}
        <li><a href="/">Home</a></li>


        {% if request.user.is_authenticated %}
        <li><a href="accounts/logout">Logout</a></li>
        {% else %}
        <li><a href="accounts/register">Register</a></li>
        <li><a href="accounts/login">Login</a></li>
        {% endif %}
    </ul>
    </div>
    {% if request.user.is_authenticated %}
        {% for cat_obj in category_list %}
            {% for post_obj in cat_obj.posts.all %}
                    {{ cat_obj }}
                <br>--------
                {{ post_obj.title }}<br>
                -------------------
                {{ post_obj.content }}
                <br>
            {% endfor %}
        {% endfor %}
    {% endif %}
{% endblock body %}

myapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign-in </button>

    <div>
        {% for message in messages %}
            <h3>{{ message }}</h3>
        {% endfor %}
    </div>
</form>
</body>
</html>

myapp/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <form action="{% url 'accounts:register' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register">

        <!--<label>
            <input type="text" name="username" placeholder="Username">
        </label><br>
        <label>
            <input type="email" name="email" placeholder="Email">
        </label><br>
        <label>
            <input type="password" name="password1" placeholder="Password">
        </label><br>
        <label>
            <input type="password" name="password2" placeholder="Confirm Password">
        </label><br>
        <input type="Submit" name="Create User">-->

    </form>

    <div>
        {% for message in messages %}
        <h3>  {{ message }}  </h3>
        {% endfor %}
    </div>

</body>
</html>